trigger: none

resources:
  pipelines:
    - pipeline: Datadog-CI
      source: DataDog.datadog-ci-azure-devops
      trigger:
        stages:
          - Test

variables:
  - group: ci-variables

stages:
  - stage: Test
    displayName: E2E tests
    jobs:
      - job: E2E
        displayName: Cross-platform end-to-end testing
        strategy:
          matrix:
            Linux:
              imageName: 'ubuntu-latest'
            # Windows:
            #   imageName: 'windows-latest'
        pool:
          vmImage: $(imageName)
        steps:
          - task: Datadog.datadog-ci-dev.synthetics-application-testing.SyntheticsRunTests@0
            displayName: Run the DEV task
            inputs:
              authenticationType: 'apiAppKeys'
              apiKey: '$(API_KEY)'
              appKey: '$(APP_KEY)'
              publicIds: '2r9-q7u-4nn,pwd-mwg-3p5'
              configPath: 'ci/e2e.config.json'
