issuer: https://token.actions.githubusercontent.com

subject: repo:DataDog/datadog-ci-azure-devops:ref:refs/heads/main

claim_pattern:
  event_name: workflow_dispatch
  ref: refs/heads/main
  ref_protected: "true"
  job_workflow_ref: DataDog/datadog-ci-azure-devops/\.github/workflows/bump-datadog-ci\.yml@refs/heads/main

permissions:
  contents: write
  pull_requests: write
