# Disable the pipeline for individual commits except on `main` merges.
# The pipeline requires a Pull Request to run.
trigger:
  branches:
    include:
      - '*'

parameters:
  - name: performRelease
    displayName: Release Production Extension
    type: boolean
    default: false
  - name: releaseSemver
    displayName: Release Production semver
    type: string
    default: Patch
    values:
      - Patch
      - Minor
      - Major

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: ci-variables
  - name: artifactPath
    value: vsix
  - name: packagedTask
    value: datadog-ci.vsix
  - name: publisherId
    value: Datadog
  - name: extensionName
    value: 'Datadog Continuous Testing'
  - name: extensionId
    value: datadog-ci
  - name: devExtensionTag
    value: -dev
  - name: contributionId
    value: synthetics-application-testing

stages:
  - stage: ReleaseDev
    displayName: Release DEV extension
    jobs:
      - job: PublishDev
        displayName: Publish DEV extension version
        steps:
          - task: SyntheticsRunTests@0
            displayName: Run deprecated task
            inputs:
              authenticationType: 'apiAppKeys'
              apiKey: '$(API_KEY)'
              appKey: '$(APP_KEY)'
              publicIds: '2r9-q7u-4nn,pwd-mwg-3p5'
              configPath: 'ci/e2e.config.json'
