# This workflow ensures LICENSE-3rdparty.csv is up-to-date with all dependencies used

name: Check dependencies license

on: push

jobs:
  check-license-3rdparty-synthetics:
    name: Check LICENSE-3rdparty.csv SyntheticsRunTestsTask
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check LICENSE-3rdparty.csv SyntheticsRunTestsTask
        run: ./ci/check-license-3rdparty.sh
